# Use the pgvector image with PostgreSQL 16
FROM pgvector/pgvector:pg16

# Set environment variables
ENV POSTGRES_PASSWORD=thepassword
ENV POSTGRES_DB=business

# Expose the PostgreSQL port
EXPOSE 5432



# Start PostgreSQL server
CMD ["postgres"]